apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
  namespace: user-management
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:16-alpine
        name: postgres
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef: 
            name: postgres-secret
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: postgres-pvc
